- alias: hasura
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: h34-nylon80-stg
  name: h34-nylon80-stg
- alias: test
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: cartwheel94
  name: cartwheel94
